### ISSUE TITLE
https://financial-charts.effingapp.com/ isn't working.

### ISSUE THREAD

**Issue by Mistletoe13** [effinggames/financial-chart#26]
https://financial-charts.effingapp.com/ isn't working.  Does anyone know how to contact the creator?  I found this chart the most useful chart about the market that exists anywhere!

https://financial-charts.effingapp.com/europe  The Europe one works but I don't find it as useful as the US one.

I wish I knew enough to use these files to make my own and host it but I don't.

**Comment by robgraeber** [comment]
Fixed

**Comment by Mistletoe13** [comment]
Thank you so much!!!

**Comment by Mistletoe13** [comment]
When does the chart update?  The last one is from July and I’ve been so
curious if stock allocation has gone down a lot this year as people take
advantage of high interest rate yields.

Thank you so much for your chart, it’s one of the best things on the
internet.

Jarrod

**Comment by laughtall** [comment]
@robgraeber stop working again

**Comment by Mistletoe13** [comment]
It’s not working again.  I miss this chart so much.
